<html>
<head>
	<link rel="stylesheet" type="text/css" href="templates/bigbenrating.css"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<div><p>Рейтинг клуба BigBen</p></div>
<div id="css-menu-wrapper">
		<div id="css-menu">
		<ul>
			<li><a href="/?action=getRating">
				<span class="text-top">Рейтинг</span>
				<span class="text-bottom">Рейтинг игроков</span>
			</a></li>
			<li><a href="/?action=getPersonalStat">
				<span class="text-top">Личный кабинет</span>
				<span class="text-bottom">Статистика игрока</span>
			</a></li>
			<li><a href="/?action=showGames">
				<span class="text-top">Подробно про игры</span>
				<span class="text-bottom">История игр</span>
			</a></li>
			
			
		</ul>
		</div>
</div>